name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Install Flutter (if needed, or remove if unrelated)
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.3'

    # Ensure you're in the correct directory and then run make
    - name: Build the project
      run: |
        cd path/to/your/project  # Adjust this to the directory where Makefile is located
        make

    # Run tests if using make
    - name: Run Tests
      run: |
        cd path/to/your/project
        make check

    # Perform make distcheck for validation
    - name: Run Distcheck
      run: |
        cd path/to/your/project
        make distcheck
    - name: Use Secret Token
      run: echo "The secret token is ${{ secrets.TOKEN }}"
      env:
          MY_SECRET_TOKEN: ${{ secrets.TOKEN }}




