name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4
    

    # Install Flutter (if needed, or remove this if unrelated)
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.3'

    # Compile the code with make
    - name: Build
      run: make

    # Run tests with make check
    - name: Run Tests
      run: make check

    # Perform make distcheck for validation
    - name: Run Distcheck
      run: make distcheck
    - name: Use Secret Token
      run: echo "The secret token is ${{ secrets.TOKEN }}"
      env:
          MY_SECRET_TOKEN: ${{ secrets.TOKEN }}


